---
root: true

extends: '@elastic/kibana'

plugins:
  - '@elastic/eslint-plugin-kibana-custom'
  - 'jest'

rules:
  no-extra-semi: off
  quotes: off
  no-shadow: error
  no-unused-vars: [error, {args: 'after-used', argsIgnorePattern: '^_'}]
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-curly-spacing: [error, always]
  kibana-custom/no-default-export: error

  jest/no-disabled-tests: error
  jest/no-focused-tests: error
  jest/no-identical-title: error

env:
  jest/globals: true

settings:
  import/resolver:
    - '@elastic/eslint-import-resolver-kibana':
        rootPackageName: x-pack
        pluginDirs:
           - ./plugins
