---
root: true

extends: '@elastic/kibana'

plugins:
  - '@elastic/eslint-plugin-kibana-custom'
  - 'jest'

rules:
  quotes: off

  jest/no-disabled-tests: error
  jest/no-focused-tests: error
  jest/no-identical-title: error

env:
  jest/globals: true

settings:
  import/resolver:
    - '@elastic/eslint-import-resolver-kibana':
        rootPackageName: x-pack
        pluginDirs:
           - ./plugins
