---
extends: '@elastic/kibana'

plugins:
  - react

ecmaFeatures:
  jsx: true

rules:
  no-var: off
  prefer-const: off
  no-extra-semi: off
  quotes: off

  no-shadow: error
  no-unused-vars: [error, {args: 'after-used', argsIgnorePattern: '^_'}]
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
