[role="xpack"]
[[monitoring-xpack-kibana]]
== Configuring Monitoring in {kib}
++++
<titleabbrev>Configuring Monitoring</titleabbrev>
++++

To monitor {kib}:

. <<installing-xpack-kb,Install {xpack}>>.

. Identify where to send monitoring data. {kib} automatically
sends metrics to the {es} cluster specified in the `elasticsearch.url` property
in `kibana.yml`. This property has a default value of `http://localhost:9200`.

. Identify where to retrieve monitoring data from. You can optionally set the
`xpack.monitoring.elasticsearch.url` in `kibana.yml`. This property enables you
to use a single {kib} instance to search and visualize data in your production
cluster as well as monitor data sent to a dedicated monitoring cluster.

. Restart {kib}.

. If {security} is enabled, to view the monitoring dashboards you must log in to
{kib} as a user who has both the `kibana_user` and `monitoring_user` roles. For
example:
+
--
[source,js]
--------------------------------------------------
POST /_xpack/security/user/stack-monitor
{
  "password" : "changeme",
  "roles" : [ "kibana_user", "monitoring_user" ]
}
--------------------------------------------------
// CONSOLE
--

See also <<monitoring-data>>.
