[role="xpack"]
[[setup-xpack-kb]]
= Set Up X-Pack

[partintro]
--
{xpack} is an Elastic Stack extension that bundles security, alerting,
monitoring, reporting, machine learning, and graph capabilities into one
easy-to-install package. To access this functionality, you must
<<installing-xpack-kb,install {xpack} in {kib}>>.

After you install {xpack}, the following pages are added to
the side navigation:

* **Machine Learning**
* **Graph**
* **Monitoring**


The **Management** page gains options related to configuring security and the
**Dev Tools** page gains a Search Profiler, which helps you inspect and
analyze your search queries. Where these and other {xpack} features are
mentioned in this documentation, we've added an icon to clearly indicate
that what you're reading pertains to features available only in {xpack}.

For more information about how to obtain {xpack},
see https://www.elastic.co/products/x-pack.
--

include::installing.asciidoc[]
include::settings/settings-xkb.asciidoc[]
